export enum Action {
  LoadIngredients = 'LOAD_INGREDIENTS',
  AddToBurger = 'ADD_TO_BURGER',
  RemoveFilling = 'REMOVE_FILLING',
  ReplaceFillings = 'REPLACE_FILLINGS',
  LoadOrder = 'LOAD_ORDER',
  DropOrder = 'DROP_ORDER',
  ShowIngredientDetail = 'SHOW_INGREDIENT_DETAIL',
  HideIngredientDetail = 'HIDE_INGREDIENT_DETAIL',
  ShowErrorMessage = 'SHOW_ERROR_MESSAGE',
  HideErrorMessage = 'HIDE_ERROR_MESSAGE',
  SelectIngredient = 'SELECT_INGREDIENT',
  SetIsLoading = 'SET_IS_LOADING',
  ShowOrderDetail = 'SHOW_ORDER_DETAIL',
  HideOrderDetail = 'HIDE_ORDER_DETAIL',
  ClearBurger = 'CLEAR_BURGER',
}
